[package]
name = "extendr-engine"
version = "0.1.11"
authors = ["andy-thomason <andy@andythomason.com>"]
edition = "2018"
description = "Safe and user friendly bindings to the R programming language."
license = "MIT"
documentation = "https://extendr.github.io/extendr/extendr_engine/index.html"
repository = "https://github.com/extendr/extendr"

[dependencies]
libR-sys = "0.1.12"
